waic/atag20-ja

docs/index.html

Issue #23 対応

---

docs/index.html

表記ゆれの修正。
s/ユーザー/ユーザ/
s/インターフェース/インタフェース/
s/注/注記

Issue #25 対応

---

docs/index.html

Issue #28 対応

---

docs/index.html

「注」→「注記」の置換漏れが2箇所ありましたので、対応しました。

Issue #25 追加対応

---

docs/index.html

ひとまずやってみましたが、fukumotoyさんがGitHub上で実名を名乗られていない様子でもあり、どう表記するか要検討です。

冒頭訳注をWCAGのスタイルに揃え、fukumotoyさんのクレジットを追加

---

docs/index.html

author の訳として、「著者」となっている箇所を、すべて「コンテンツ制作者」としました。

Issue #39 対応

---

docs/index.html

英語文書 (W3C サイト) へのリンク箇所について、リンクラベルを英語に戻しました。

Issue #43 対応

---

docs/index.html

澤田さんのご指摘 (A.3.6.1 などで「ディスプレイの設定」とあるが、物理的なイメージが強い印象を受けるので「画面設定」としては？) について、WCAG WG4 内で検討し、「ディスプレイ設定」を「表示設定」としたいと思います。

Issue #50 対応

---

docs/index.html

(For the authoring tool user interface) の訳として、(オーサリングツールのユーザインタフェースに対して) を (オーサリングツールのユーザインタフェース向け) に変更しました。

Issue #46 対応

---

docs/index.html

 "Combined User Agent" は「統合ユーザエージェント」に統一。 #34

---

docs/index.html

「時間依存」に統一 #79

---

docs/index.html

「よりアクセシブル」に修正 #44

---

docs/index.html

「少なくとも同程度目立つ」に統一 #82

---

docs/index.html

ガイドラインA.2.2の Implementing へのリンクを修正しました。
レビューをお願いします。

ガイドラインA.2.2の Implementing へのリンクを修正 #107

---

docs/index.html

issue #27 に記載の方針で修正しました。
そもそもこの方針が正しくないなど、何度かフィードバックがあることを想定しております。
修正箇所が多くお手数をおかけしますが、何卒よろしくお願いいたします。

用語の後に原文を併記 #27

---

docs/index.html

issue #47 の解釈は正しいでしょうか。
指摘以外にも該当箇所がありましたので、併せて修正しています。
レビューをお願いします。

「プレゼンテーション」を「提示」に修正 #47

---

docs/index.html

付録B、付録Cのですます調を修正しています。
気になっている部分はコミットにコメントを追記しています。
ご確認をよろしくお願いいたします。

ですます調を修正。 #115

---

docs/index.html

「関連付け」への修正 #78

---

docs/index.html

close #88
「2つ」であった箇所は、すべて数えている箇所と判断して「二つ」に修正しました。
確認をお願いします。

「二つ」への修正 #88

---

docs/index.html

close #113
用語だけでなく、関連する箇所も併せて修正しています。
よろしくお願いいたします。

「プログラムにより関連付けられる代替コンテンツ」への修正 #113

---

docs/index.html

close #87
「1つ」であった箇所は、すべて数えている箇所と判断して「一つ」に修正しました。
確認をお願いします。

「一つ」への修正 #87

---

docs/index.html

「最低限」に統一 #118

---

docs/index.html

以下のフォーマットに統一しました。
- 「例えば」の後に読点 (、) を入れる。
- 「など」の手前に読点 (、) を入れる。
- 複数の事項を、「～たり…たり」の呼応で記述する。

「コンテンツ変換 (content transformations)」における、箇条書きの「例えば...」の表記スタイル統一。

---

docs/index.html

作業進行中表記を削除
